[package]
name = "polymatheia"
version = "0.2.0"
authors = ["Mathias Blarer <mblarer@protonmail.ch>"]
edition = "2021"
description = "Mathematical functions and algorithms in pure and safe Rust."
repository = "https://github.com/mblarer/polymatheia/"
license = "MIT OR Apache-2.0"
